### ISSUE TITLE
The 6th question DAY2  solution is not added ..... the output csv file is blank

### ISSUE THREAD

**Issue by ombharamadev** [Apollo-bot35/ASSIGNMENTS#1]
![image](https://github.com/Apollo-bot35/ASSIGNMENTS/assets/150242178/c62a5ec4-9994-4e44-8491-1c37442e1d9d)
The 6th question solution is not added  the output csv file is blank and not added screenshot of 6th program solution image

**Comment by Apollo-bot35** [comment]
Ok sir will do it

**Comment by Apollo-bot35** [comment]
Sir done added the screenshot and the program updated..
https://github.com/Apollo-bot35/ASSIGNMENTS.git

**Comment by ombharamadev** [comment]
good work

**Comment by Apollo-bot35** [comment]
Glad to hear it!
